ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.snk.conferencia.ApplicationKt.module ]
    }
}

sankhya {
    prodUrl = "https://sankhya.stoky.com.br"
    prodUrl = ${?PROD_URL}
    prodUrl = ${?SANKHYA_PROD_URL}
    
    treinaUrl = "https://teste.stoky.com.br"
    treinaUrl = ${?TREINA_URL}
    treinaUrl = ${?SANKHYA_TREINA_URL}
}

jwt {
    secret = "snk-conferencia-secret-key-production-min-256-bits-super-secure"
    secret = ${?JWT_SECRET}
    issuer = "snk-conferencia"
    audience = "snk-conferencia-users"
    realm = "snk-conferencia-realm"
}
